# Basic Site Configuration
title: My GitHub Pages Site
description: A website built using GitHub Pages
baseurl: ""  # the subpath of your site, e.g. /blog
url: "caspian.rosengren.nu"  # the base hostname & protocol, e.g. http://example.com

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Build settings
markdown: kramdown
theme: minima  # You can change this to any theme supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Collections (optional)
collections:
  projects:
    output: true
    permalink: /projects/:path/
